FORMAT: 1A
HOST: https://what/

# Yakes-HILDA

App API Documentation of Telkomsehat Hilda Module

# Yakes-HILDA API Root [/prod/hilda/]

Default Endpoint

## Questionnaire Collection [/questionnaire/{questionnaire_id}]

+ question
+ published_at - An ISO8601 date when the question was published.
+ url
+ choices - An array of Choice objects.

+ Parameters
    + questionnaire_id: 1 (required, string) - ID of the Questionnaire in form of an string

### List All Questionnaire [GET]

This Endpoint Will Give All Avai

+ Response 200 (application/json)

        {
            "question": "Favourite programming language?",
            "published_at": "2015-08-05T08:40:51.620Z",
            "choices": [
                {
                    "choice": "Swift",
                    "votes": 2048
                }, {
                    "choice": "Python",
                    "votes": 1024
                }, {
                    "choice": "Objective-C",
                    "votes": 512
                }, {
                    "choice": "Ruby",
                    "votes": 256
                }
            ]
        }

## Questionnaire Response Collection [/questionnaire/response]

### Create a New Questionnaire Response [POST]

Create A New Questionnaire Response, This Example is Based on Questionnaire Type 1

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
